### ISSUE TITLE
Template literals are used incorrectly

### ISSUE THREAD

**Issue by chekit** [happyBanshee/aab-server#1]
> I'm sorry for not creating a pull request instead of issue. 

In `server.js` file on line 32 the template literals are used incorrectly, which leads to the incorrect reflection in the console once the server is started:

```sh
Server is running on http://localhost:${port}
```

## Issue

https://github.com/happyBanshee/aab-server/blob/84e0f0e0c0dee0b36c4e39cf0e015fdcaa58dab0/server.js#L32

## The fix

```javascript
console.log(`Server is running on http://localhost:${port}`);
```

**Comment by happyBanshee** [comment]
Thank you!
